# Generated by Django 4.2.7 on 2025-11-24 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of', to='chat.user'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_member_limit',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_privacy',
            field=models.CharField(blank=True, choices=[('public', 'Public - Anyone can join'), ('invite', 'Invite Only - Need invite to join'), ('closed', 'Closed - Admin only')], default='public', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
