# Generated by Django 4.2.7 on 2025-11-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_description_conversation_group_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_delete_hours',
            field=models.IntegerField(default=3),
        ),
    ]
